### ISSUE TITLE
Cell background

### ISSUE THREAD

**Issue by kobalicek** [6pac/SlickGrid#89]
Thanks for this fork!

While using SlickGrid I faced an issue that I cannot programatically set a background value of a column/cell. The problem is that I need a raw style, not just css class name.

I workarounded the issue by doing this.

```css
.slick-cell {
  box-sizing: border-box;
  min-height: 100%;
  max-height: 100%;
  padding: 0px;
}

.slick-cell-content {
  display: inline-block;
  box-sizing: border-box;
  width: 100%;
  height: 100%;
  padding: 1px 2px;
}
```

and then by using a custom formatter, that works like this:

```js
function formatter(row, cell, value, columnDef, dataContext) {
  const extra = value.background ? ` style="background: ${value.background};"` : "";
  return `<span class="slick-cell-content"${extra}>` + value.toHTML() + `</span>`;
}
```

While it works I don't like this solution and I don't trust it works everywhere.

What about adding a `backgroundFormatter` to a column object, if it's a function it would be called to return a background style that will be added to that cell. I think this will be a really small and non-invasive change, allowing people to better customize cell rendering.

If you agree I would do PR myself, just wanted to ask if this has a chance to be merged.
